"""Cython --embed pipeline with a Visual Studio 2022 project.

Flow:
  1. Cython 3.0.11 transpiles entry.py -> entry.c (/* Generated by Cython */).
  2. A .vcxproj + .sln wrapping that C file is generated.
  3. MSBuild (Visual Studio 2022) compiles it to EXE.
  4. Visual Studio auto-generates the debug binaries (PDB) via /Zi + /DEBUG.
"""
from __future__ import annotations

import shutil
import subprocess
import uuid
from pathlib import Path


def ensure_cython(python_exe: Path, version: str = "3.0.11") -> None:
    """Install the pinned Cython into the Python 3.14 environment if missing."""
    probe = subprocess.run(
        [str(python_exe), "-m", "cython", "--version"],
        capture_output=True, text=True, timeout=60,
    )
    if probe.returncode == 0 and version in (probe.stdout + probe.stderr):
        print(f"[cpythonizer] Cython {version} OK")
        return
    print(f"[cpythonizer] Installing Cython=={version} ...")
    r = subprocess.run(
        [str(python_exe), "-m", "pip", "install", f"cython=={version}"],
        timeout=300,
    )
    if r.returncode != 0:
        raise RuntimeError("pip install cython failed")


def cythonize_embed(python_exe: Path, entry: Path, workdir: Path) -> Path:
    """Run `cython --embed` on the entry file. Returns the generated .c path."""
    workdir.mkdir(parents=True, exist_ok=True)
    out_c = workdir / (entry.stem + ".c")
    print(f"[cpythonizer] Cython transpiling: {entry} -> {out_c}")
    r = subprocess.run(
        [str(python_exe), "-m", "cython", "--embed", "-3",
         "--output-file", str(out_c), str(entry)],
        capture_output=True, text=True, timeout=300,
    )
    print((r.stdout or "")[-2000:])
    if r.returncode != 0 or not out_c.is_file():
        raise RuntimeError(f"Cython failed:\n{r.stdout}\n{r.stderr}")
    # Sanity: must be genuine Cython output.
    head = out_c.read_text(encoding="utf-8", errors="replace")[:2000]
    if "Generated by Cython" not in head:
        raise RuntimeError("Generated file is not Cython output")
    print(f"[cpythonizer] C generated ({out_c.stat().st_size // 1024} KB)")
    return out_c


def find_msbuild(vs_root: Path) -> Path:
    """Locate MSBuild.exe inside the VS2022 install."""
    p = vs_root / "MSBuild" / "Current" / "Bin" / "MSBuild.exe"
    if p.is_file():
        return p
    raise FileNotFoundError(f"MSBuild.exe not found under {vs_root}")


VCXPROJ_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <VCProjectVersion>17.0</VCProjectVersion>
    <ProjectGuid>{GUID}</ProjectGuid>
    <RootNamespace>{NAME}</RootNamespace>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>v143</PlatformToolset>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings" />
  <ImportGroup Label="Shared" />
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutDir>{OUTDIR}\\</OutDir>
    <IntDir>{INTDIR}\\</IntDir>
    <TargetName>{NAME}</TargetName>
    <!-- Debug binaries auto-generated by VS: -->
    <GenerateDebugInformation>true</GenerateDebugInformation>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <Optimization>MaxSpeed</Optimization>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>NDEBUG;_CONSOLE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
      <LanguageStandard>stdcpp17</LanguageStandard>
      <!-- C file compiled as C; Python headers: -->
      <AdditionalIncludeDirectories>{INCLUDE};%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
    </ClCompile>
    <Link>
      <SubSystem>Console</SubSystem>
      <GenerateDebugInformation>true</GenerateDebugInformation>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <AdditionalLibraryDirectories>{LIBDIR};%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>{LIBNAME};kernel32.lib;user32.lib;advapi32.lib;ws2_32.lib;version.lib;shlwapi.lib;ole32.lib;shell32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <EntryPointSymbol>wmainCRTStartup</EntryPointSymbol>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="{CFILE}" />
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets" />
</Project>
"""

SLN_TEMPLATE = """Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 17
VisualStudioVersion = 17.0.0.0
MinimumVisualStudioVersion = 10.0.40219.1
Project("{{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}}") = "{NAME}", "{NAME}.vcxproj", "{{GUID}}"
EndProject
Global
\tGlobalSection(SolutionConfigurationPlatforms) = preSolution
\t\tRelease|x64 = Release|x64
\tEndGlobalSection
\tGlobalSection(ProjectConfigurationPlatforms) = postSolution
\t\t{{GUID}}.Release|x64.ActiveCfg = Release|x64
\t\t{{GUID}}.Release|x64.Build.0 = Release|x64
\tEndGlobalSection
EndGlobal
"""


def generate_vs_project(workdir: Path, app_name: str, c_file: Path,
                        include_dir: Path, lib_dir: Path, lib_name: str,
                        out_dir: Path) -> Path:
    """Write .vcxproj + .sln into workdir. Returns the .sln path."""
    guid = str(uuid.uuid4()).upper()
    intdir = workdir / "obj"
    proj = VCXPROJ_TEMPLATE.format(
        GUID="{" + guid + "}",
        NAME=app_name,
        OUTDIR=str(out_dir),
        INTDIR=str(intdir),
        INCLUDE=str(include_dir),
        LIBDIR=str(lib_dir),
        LIBNAME=lib_name,
        CFILE=str(c_file),
    )
    vcxproj = workdir / f"{app_name}.vcxproj"
    vcxproj.write_text(proj, encoding="utf-8")
    sln = workdir / f"{app_name}.sln"
    sln.write_text(
        SLN_TEMPLATE.format(NAME=app_name, GUID="{" + guid + "}"),
        encoding="utf-8",
    )
    print(f"[cpythonizer] VS project written:\n  {vcxproj}\n  {sln}")
    return sln


def build_sln(msbuild: Path, sln: Path) -> None:
    """Build Release|x64 with MSBuild. PDB is produced automatically."""
    print(f"[cpythonizer] MSBuild Release|x64: {sln.name}")
    r = subprocess.run(
        [str(msbuild), str(sln), "/p:Configuration=Release", "/p:Platform=x64",
         "/verbosity:minimal", "/nologo"],
        capture_output=True, text=True, timeout=1200,
    )
    print((r.stdout or "")[-4000:])
    if r.returncode != 0:
        raise RuntimeError(f"MSBuild failed:\n{r.stdout}\n{r.stderr}")
    print("[cpythonizer] MSBuild OK (EXE + PDB generated by Visual Studio)")


def build(entry: str | Path, name: str | None = None, dist: str | Path = "dist",
          vs_root: Path | None = None, python_exe: Path | None = None) -> Path:
    """Full pipeline: Cython --embed -> .vcxproj/.sln -> MSBuild -> EXE+PDB."""
    from .python_env import ensure_python314, PyDev
    from .vs import ensure_vs2022

    entry_p = Path(entry).resolve()
    if not entry_p.is_file():
        raise FileNotFoundError(f"Entry not found: {entry_p}")
    app_name = name or entry_p.stem

    py = Path(python_exe) if python_exe else ensure_python314(auto_install=False)
    dev = PyDev(py)
    dev.check()
    ensure_cython(py)

    root = vs_root or ensure_vs2022(auto_install=False)
    msbuild = find_msbuild(root)

    work = (Path("build") / f"cython_{app_name}").resolve()
    if work.exists():
        shutil.rmtree(work, ignore_errors=True)
    work.mkdir(parents=True, exist_ok=True)
    out_dir = (Path(dist).resolve() / app_name)
    out_dir.mkdir(parents=True, exist_ok=True)

    # 1) Python -> C via Cython (the /* Generated by Cython */ file).
    c_file = cythonize_embed(py, entry_p, work)

    # 2) Wrap it in a Visual Studio project.
    sln = generate_vs_project(
        work, app_name, c_file,
        dev.include, dev.libs, dev.lib_file().name,
        out_dir,
    )

    # 3) Compile with Visual Studio; PDB comes out automatically.
    build_sln(msbuild, sln)

    exe = out_dir / f"{app_name}.exe"
    pdb = out_dir / f"{app_name}.pdb"
    if not exe.is_file():
        raise RuntimeError(f"Build finished but EXE missing: {exe}")
    print(f"[cpythonizer] DONE:\n  EXE: {exe}\n  PDB: {pdb if pdb.is_file() else 'MISSING!'}")

    # 4) Required runtime copies next to the EXE (target PC has no Python).
    for dll in dev.runtime_dlls():
        shutil.copy2(dll, out_dir / dll.name)
        print(f"  + {dll.name} (runtime copy)")
    return exe
