"""Cython --embed pipeline with a Visual Studio project.

Flow:
  1. Cython 3.0.11 transpiles entry.py -> entry.c (/* Generated by Cython */).
  2. A .vcxproj + .sln wrapping that C file is generated (toolset v145 for
     Visual Studio 2026, v143 for 2022).
  3. MSBuild (Visual Studio 2026 / 2022) compiles it to EXE.
  4. Visual Studio auto-generates the debug binaries (PDB) via /Zi + /DEBUG.
  5. The stdlib is staged as python314.zip + extension .pyd files next to
     the EXE, so the app boots on a PC with no Python installed.
"""
from __future__ import annotations

import shutil
import struct
import subprocess
import uuid
import zipfile
from pathlib import Path


def prepare_icon(icon_path: str | Path | None, workdir: Path, app_name: str) -> tuple[Path | None, Path | None]:
    """Process .ico or .png into an ICO and an RC file.

    Returns (rc_file, ico_file) or (None, None).
    """
    if not icon_path:
        return None, None

    icon_p = Path(icon_path).resolve()
    if not icon_p.is_file():
        raise FileNotFoundError(f"Icon file not found: {icon_p}")

    workdir.mkdir(parents=True, exist_ok=True)
    ico_dest = workdir / f"{app_name}.ico"
    suffix = icon_p.suffix.lower()

    if suffix == ".ico":
        shutil.copy2(icon_p, ico_dest)
    elif suffix == ".png":
        converted = False
        try:
            from PIL import Image
            img = Image.open(icon_p)
            sizes = [(256, 256), (128, 128), (64, 64), (48, 48), (32, 32), (16, 16)]
            valid = [s for s in sizes if s[0] <= max(img.width, 16)] or [(img.width, img.height)]
            img.save(ico_dest, format="ICO", sizes=valid)
            converted = True
        except ImportError:
            pass

        if not converted:
            png_bytes = icon_p.read_bytes()
            if len(png_bytes) < 24 or png_bytes[:8] != b"\x89PNG\r\n\x1a\n":
                raise ValueError(f"File is not a valid PNG image: {icon_p}")
            width = int.from_bytes(png_bytes[16:20], "big")
            height = int.from_bytes(png_bytes[20:24], "big")
            bw = width if width < 256 else 0
            bh = height if height < 256 else 0
            header = struct.pack("<HHH", 0, 1, 1)
            entry = struct.pack("<BBBBHHII", bw, bh, 0, 0, 1, 32, len(png_bytes), 22)
            ico_dest.write_bytes(header + entry + png_bytes)
        print(f"[cpythonizer] Icon prepared from PNG: {ico_dest.name}")
    else:
        raise ValueError(f"Unsupported icon format: {suffix} (expected .ico or .png)")

    rc_file = workdir / f"{app_name}.rc"
    rc_file.write_text(f'1 ICON "{ico_dest.name}"\n', encoding="utf-8")
    return rc_file, ico_dest


def ensure_cython(python_exe: Path, version: str = "3.0.11") -> None:
    """Install the pinned Cython into the Python 3.14 environment if missing."""
    probe = subprocess.run(
        [str(python_exe), "-m", "cython", "--version"],
        capture_output=True, text=True, timeout=60,
    )
    if probe.returncode == 0 and version in (probe.stdout + probe.stderr):
        print(f"[cpythonizer] Cython {version} OK")
        return
    print(f"[cpythonizer] Installing Cython=={version} ...")
    r = subprocess.run(
        [str(python_exe), "-m", "pip", "install", f"cython=={version}"],
        timeout=300,
    )
    if r.returncode != 0:
        raise RuntimeError("pip install cython failed")


def cythonize_embed(python_exe: Path, entry: Path, workdir: Path, embed: bool = True, release: bool = False) -> Path:
    """Run `cython --embed` on the entry file. Returns the generated .c path."""
    workdir.mkdir(parents=True, exist_ok=True)
    out_c = workdir / (entry.stem + ".c")
    print(f"[cpythonizer] Cython transpiling: {entry} -> {out_c}")
    cmd = [str(python_exe), "-m", "cython"]
    if embed:
        cmd.append("--embed")
    if release:
        cmd.extend([
            "-X", "boundscheck=False",
            "-X", "wraparound=False",
            "-X", "initializedcheck=False",
            "-X", "cdivision=True",
        ])
    cmd.extend(["-3", "--output-file", str(out_c), str(entry)])
    r = subprocess.run(
        cmd,
        capture_output=True, text=True, timeout=300,
    )
    print((r.stdout or "")[-2000:])
    if r.returncode != 0 or not out_c.is_file():
        raise RuntimeError(f"Cython failed:\n{r.stdout}\n{r.stderr}")
    # Sanity: must be genuine Cython output.
    head = out_c.read_text(encoding="utf-8", errors="replace")[:2000]
    if "Generated by Cython" not in head:
        raise RuntimeError("Generated file is not Cython output")
    print(f"[cpythonizer] C generated ({out_c.stat().st_size // 1024} KB)")
    return out_c


def find_msbuild(vs_root: Path) -> Path:
    """Locate MSBuild.exe inside a Visual Studio install root."""
    from .vs import VsInstall, resolve_releases

    # Any release layout works: only the folder name differs per VS version.
    p = VsInstall(resolve_releases("auto")[0], vs_root).msbuild()
    if p is not None:
        return p
    raise FileNotFoundError(f"MSBuild.exe not found under {vs_root}")


VCXPROJ_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Release|x64">
      <Configuration>Release</Configuration>
      <Platform>x64</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <VCProjectVersion>{PROJECT_VERSION}</VCProjectVersion>
    <ProjectGuid>{GUID}</ProjectGuid>
    <RootNamespace>{NAME}</RootNamespace>
    <WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.Default.props" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">
    <ConfigurationType>Application</ConfigurationType>
    <UseDebugLibraries>false</UseDebugLibraries>
    <PlatformToolset>{TOOLSET}</PlatformToolset>
    <WholeProgramOptimization>true</WholeProgramOptimization>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />
  <ImportGroup Label="ExtensionSettings" />
  <ImportGroup Label="Shared" />
  <ImportGroup Label="PropertySheets" Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props" Condition="exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')" Label="LocalAppDataPlatform" />
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <OutDir>{OUTDIR}\\</OutDir>
    <IntDir>{INTDIR}\\</IntDir>
    <TargetName>{NAME}</TargetName>
    <GenerateDebugInformation>{GENERATE_DEBUG}</GenerateDebugInformation>
  </PropertyGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <Optimization>MaxSpeed</Optimization>
      <FunctionLevelLinking>true</FunctionLevelLinking>
      <IntrinsicFunctions>true</IntrinsicFunctions>
      <SDLCheck>true</SDLCheck>
      <PreprocessorDefinitions>NDEBUG;{DEF_SUBSYSTEM};%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <ConformanceMode>true</ConformanceMode>
      <LanguageStandard>stdcpp17</LanguageStandard>
      <!-- C file compiled as C; Python headers: -->
      <AdditionalIncludeDirectories>{INCLUDE};%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
      <DebugInformationFormat>{DEBUG_FORMAT}</DebugInformationFormat>
    </ClCompile>
    <Link>
      <SubSystem>{SUBSYSTEM}</SubSystem>
      <GenerateDebugInformation>{GENERATE_DEBUG}</GenerateDebugInformation>
      <EnableCOMDATFolding>true</EnableCOMDATFolding>
      <OptimizeReferences>true</OptimizeReferences>
      <AdditionalLibraryDirectories>{LIBDIR};%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>{LIBNAME};kernel32.lib;user32.lib;advapi32.lib;ws2_32.lib;version.lib;shlwapi.lib;ole32.lib;shell32.lib;%(AdditionalDependencies)</AdditionalDependencies>
      <EntryPointSymbol>wmainCRTStartup</EntryPointSymbol>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="{CFILE}" />
{RESOURCE_ITEM}
  </ItemGroup>
  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets" />
</Project>
"""

SLN_TEMPLATE = """Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version {SLN_MAJOR}
VisualStudioVersion = {SLN_MAJOR}.0.0.0
MinimumVisualStudioVersion = 10.0.40219.1
{PROJECTS}
Global
\tGlobalSection(SolutionConfigurationPlatforms) = preSolution
\t\tRelease|x64 = Release|x64
\tEndGlobalSection
\tGlobalSection(ProjectConfigurationPlatforms) = postSolution
{CONFIGS}
\tEndGlobalSection
EndGlobal
"""


def generate_vs_project(workdir: Path, app_name: str, c_file: Path,
                        include_dir: Path, lib_dir: Path, lib_name: str,
                        out_dir: Path, release=None, rc_file: Path | None = None,
                        release_mode: bool = False, noconsole: bool = False,
                        keep_pdb: bool = False,
                        local_modules: list | None = None) -> Path:
    """Write .vcxproj + .sln into workdir. Returns the .sln path.

    The project is stamped for the targeted Visual Studio release, so the
    toolset (v145 on VS2026, v143 on VS2022) always matches the MSBuild that
    is about to compile it.
    """
    from .vs import VS2022, VsRelease
    from .local_modules import generate_local_pyd_project

    release: VsRelease = release or VS2022
    guid = str(uuid.uuid4()).upper()
    intdir = workdir / "obj"
    resource_item = f'    <ResourceCompile Include="{rc_file.name}" />' if rc_file else ""
    subsystem = "Windows" if noconsole else "Console"
    def_subsystem = "_WINDOWS" if noconsole else "_CONSOLE"
    generate_debug = "true" if (keep_pdb or not release_mode) else "false"
    debug_format = "ProgramDatabase" if (keep_pdb or not release_mode) else "None"
    proj = VCXPROJ_TEMPLATE.format(
        GUID="{" + guid + "}",
        NAME=app_name,
        PROJECT_VERSION=release.project_version,
        TOOLSET=release.toolset,
        OUTDIR=str(out_dir),
        INTDIR=str(intdir),
        INCLUDE=str(include_dir),
        LIBDIR=str(lib_dir),
        LIBNAME=lib_name,
        CFILE=str(c_file),
        RESOURCE_ITEM=resource_item,
        SUBSYSTEM=subsystem,
        DEF_SUBSYSTEM=def_subsystem,
        GENERATE_DEBUG=generate_debug,
        DEBUG_FORMAT=debug_format,
    )
    vcxproj = workdir / f"{app_name}.vcxproj"
    vcxproj.write_text(proj, encoding="utf-8")

    project_blocks = [
        f'Project("{{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}}") = "{app_name}", "{app_name}.vcxproj", "{{{{{guid}}}}}"\nEndProject'
    ]
    config_blocks = [
        f'\t\t{{{{{guid}}}}}.Release|x64.ActiveCfg = Release|x64\n\t\t{{{{{guid}}}}}.Release|x64.Build.0 = Release|x64'
    ]

    for mod in (local_modules or []):
        generate_local_pyd_project(
            workdir=workdir, mod=mod, stage_dir=out_dir,
            include_dir=include_dir, lib_dir=lib_dir, lib_name=lib_name,
            release=release, release_mode=release_mode, keep_pdb=keep_pdb,
        )
        project_blocks.append(
            f'Project("{{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}}") = "{mod.proj_name}", "{mod.proj_name}.vcxproj", "{{{{{mod.guid}}}}}"\nEndProject'
        )
        config_blocks.append(
            f'\t\t{{{{{mod.guid}}}}}.Release|x64.ActiveCfg = Release|x64\n\t\t{{{{{mod.guid}}}}}.Release|x64.Build.0 = Release|x64'
        )

    sln = workdir / f"{app_name}.sln"
    sln.write_text(
        SLN_TEMPLATE.format(
            SLN_MAJOR=release.major,
            PROJECTS="\n".join(project_blocks),
            CONFIGS="\n".join(config_blocks),
        ),
        encoding="utf-8",
    )
    print(f"[cpythonizer] {release.label} project written ({release.toolset}, {subsystem}):\n  {vcxproj}\n  {sln}")
    return sln


def build_sln(msbuild: Path, sln: Path) -> None:
    """Build Release|x64 with MSBuild. PDB is produced automatically."""
    print(f"[cpythonizer] MSBuild Release|x64: {sln.name}")
    r = subprocess.run(
        [str(msbuild), str(sln), "/p:Configuration=Release", "/p:Platform=x64",
         "/verbosity:minimal", "/nologo"],
        capture_output=True, text=True, timeout=1200,
    )
    print((r.stdout or "")[-4000:])
    if r.returncode != 0:
        raise RuntimeError(f"MSBuild failed:\n{r.stdout}\n{r.stderr}")
    print("[cpythonizer] MSBuild OK (EXE + PDB generated by Visual Studio)")


def build(entry: str | Path, name: str | None = None, dist: str | Path = "dist",
          vs: str = "auto", vs_root: Path | None = None,
          python_exe: Path | None = None, embed: bool = True,
          onefile: bool = False, icon: str | Path | None = None,
          include_packages: list[str] | None = None,
          release: bool = False, noconsole: bool = False,
          keep_pdb: bool = False, compress: str = "none",
          lzma_preset: int = 9, lzma_extreme: bool = True,
          encrypt: bool = True, obfuscate: bool = False) -> Path:
    """Full pipeline: Cython --embed -> .vcxproj/.sln -> MSBuild -> EXE+PDB.

    With onefile=True the program and its runtime are staged under build/ and
    the result is a single self-extracting EXE in dist/<app>/<app>.exe.
    """
    from .python_env import ensure_python314, PyDev
    from .vs import ensure_vs

    entry_p = Path(entry).resolve()
    if not entry_p.is_file():
        raise FileNotFoundError(f"Entry not found: {entry_p}")
    app_name = name or entry_p.stem

    py = Path(python_exe) if python_exe else ensure_python314(auto_install=False)
    dev = PyDev(py)
    dev.check()
    ensure_cython(py)

    if vs_root is not None:
        from .vs import VS2022, VsInstall
        install = VsInstall(VS2022, Path(vs_root))
    else:
        install = ensure_vs(vs, auto_install=False)
    msbuild = find_msbuild(install.root)

    work = (Path("build") / f"cython_{app_name}").resolve()
    if work.exists():
        shutil.rmtree(work, ignore_errors=True)
    work.mkdir(parents=True, exist_ok=True)
    out_dir = (Path(dist).resolve() / app_name)
    # Start clean so stale files (e.g. previously staged debug .pyd) never remain.
    if out_dir.exists():
        shutil.rmtree(out_dir, ignore_errors=True)
    out_dir.mkdir(parents=True, exist_ok=True)
    # In onefile mode nothing may sit next to the final EXE: the program and
    # its runtime are staged in build/ and packed into the EXE itself.
    stage_dir = out_dir
    if onefile:
        stage_dir = (Path("build") / f"onefile_{app_name}").resolve()
        if stage_dir.exists():
            shutil.rmtree(stage_dir, ignore_errors=True)
        stage_dir.mkdir(parents=True, exist_ok=True)

    rc_file, ico_file = prepare_icon(icon, work, app_name)

    # 0) Scan for local modules/packages (self imports)
    from .local_modules import scan_local_modules, cythonize_local_module
    local_modules = scan_local_modules(entry_p)
    if local_modules:
        mod_names = [m.mod_name for m in local_modules]
        print(f"[cpythonizer] Discovered {len(local_modules)} local/self module(s): {', '.join(mod_names)}")

    # 0b) Optional obfuscator pre-processing: strip inline and line comments
    entry_to_transpile = entry_p
    if obfuscate:
        from .obfuscator import strip_comments
        obf_dir = work / "obf_src"
        obf_dir.mkdir(parents=True, exist_ok=True)
        print(f"[cpythonizer] Obfuscator: Stripping comments from entry and local modules...")
        obf_entry = obf_dir / entry_p.name
        obf_entry.write_text(strip_comments(entry_p.read_text(encoding="utf-8")), encoding="utf-8")
        entry_to_transpile = obf_entry
        for mod in local_modules:
            obf_mod = obf_dir / f"{mod.safe_name}.py"
            obf_mod.write_text(strip_comments(mod.source_py.read_text(encoding="utf-8")), encoding="utf-8")
            mod.source_py = obf_mod

    # 1) Python -> C via Cython (the /* Generated by Cython */ file).
    c_file = cythonize_embed(py, entry_to_transpile, work, embed=embed, release=release)
    for mod in local_modules:
        cythonize_local_module(py, mod, work, release=release)

    # 2) Wrap it in a Visual Studio project (EXE + .pyd modules).
    sln = generate_vs_project(
        work, app_name, c_file,
        dev.include, dev.libs, dev.lib_file().name,
        stage_dir, install.release,
        rc_file=rc_file,
        release_mode=release,
        noconsole=noconsole,
        keep_pdb=keep_pdb,
        local_modules=local_modules,
    )

    # 3) Compile with Visual Studio; PDB comes out automatically unless release mode.
    build_sln(msbuild, sln)

    # Clean up intermediate .lib and .exp files from stage_dir
    for leftover in stage_dir.rglob("*.exp"):
        leftover.unlink(missing_ok=True)
    for leftover in stage_dir.rglob("*.lib"):
        leftover.unlink(missing_ok=True)

    exe = stage_dir / f"{app_name}.exe"
    pdb = stage_dir / f"{app_name}.pdb"
    if not exe.is_file():
        raise RuntimeError(f"Build finished but EXE missing: {exe}")
    emit_debug = keep_pdb or (not release)
    if emit_debug and pdb.is_file():
        print(f"[cpythonizer] Program built:\n  EXE: {exe}\n  PDB: {pdb}")
    else:
        print(f"[cpythonizer] Program built (Release / Optimized):\n  EXE: {exe}")

    for mod in local_modules:
        pyd_path = stage_dir / mod.target_rel_dir / f"{mod.target_stem}.pyd"
        if pyd_path.is_file():
            print(f"  + {mod.mod_name} -> {pyd_path.relative_to(stage_dir)} (.pyd extension module)")

    # 4) Required runtime copies next to the EXE (target PC has no Python).
    for dll in dev.runtime_dlls():
        shutil.copy2(dll, stage_dir / dll.name)
        print(f"  + {dll.name} (runtime copy)")

    # 5) Stdlib + extension modules so the EXE boots on a bare PC.
    stage_stdlib(dev, stage_dir)

    # 5b) Third-party packages (requests, urllib3, numpy, etc.)
    from .packages import scan_imports, collect_packages, stage_third_party
    modules_to_find = set(include_packages or [])
    all_source_files = [entry_p] + [m.source_py for m in local_modules]
    local_top_names = {m.mod_name.split(".")[0] for m in local_modules}
    modules_to_find.update(scan_imports(all_source_files, exclude_names=local_top_names))
    if modules_to_find:
        pkg_data = collect_packages(py, modules_to_find)
        if pkg_data:
            print(f"[cpythonizer] Staging third-party packages: {', '.join(pkg_data.keys())}")
            stage_third_party(dev, stage_dir, pkg_data)

    # 6) Onefile: fold program + runtime into a single self-extracting EXE.
    if onefile:
        from .onefile import assemble
        return assemble(stage_dir, app_name, work, msbuild, install.release,
                        out_dir / f"{app_name}.exe", icon=ico_file,
                        release_mode=release, noconsole=noconsole,
                        keep_pdb=keep_pdb, compress=compress,
                        lzma_preset=lzma_preset, lzma_extreme=lzma_extreme,
                        encrypt=encrypt)

    if emit_debug and pdb.is_file():
        print(f"[cpythonizer] DONE:\n  EXE: {exe}\n  PDB: {pdb}")
    else:
        print(f"[cpythonizer] DONE (Release):\n  EXE: {exe}")
    return exe


def stage_stdlib(dev, out_dir: Path) -> None:
    """Stage python314.zip (Lib) and .pyd/.dll files next to the EXE.

    A Cython --embed EXE derives its module search path from its own
    folder (like the official embeddable package): it looks for
    <exe_dir>/python314.zip, then <exe_dir>/Lib. Without one of those,
    startup fails with "Could not find platform independent libraries".
    """
    from .python_env import PyDev  # noqa: F401  (type hint only)

    lib_root: Path = dev.lib_dir
    zip_name = f"python{dev.ver}.zip"  # e.g. python314.zip
    zip_path = out_dir / zip_name

    # Zip the whole Lib/ except tests, caches and idle tooling.
    skip_dirs = {"__pycache__", "test", "tests", "idlelib", "turtledemo"}
    skip_suffix = (".pyc", ".pyo", ".pdb", ".lib")
    count = 0
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for src in sorted(lib_root.rglob("*")):
            if not src.is_file():
                continue
            if src.suffix in skip_suffix:
                continue
            rel = src.relative_to(lib_root)
            if any(part in skip_dirs for part in rel.parts):
                continue
            zf.write(src, rel.as_posix())
            count += 1
    print(f"  + {zip_name} ({count} stdlib files, {zip_path.stat().st_size // 1024} KB)")

    # Extension modules (*.pyd) live in DLLs/; copy them beside the EXE
    # exactly like the official embeddable package does.
    dlls_src: Path = dev.dlls_dir
    pyd_count = 0
    if dlls_src.is_dir():
        for pyd in sorted(dlls_src.glob("*.pyd")):
            # Skip debug builds (*_d.pyd need Debug CRT) and test modules.
            stem = pyd.stem.lower()
            if stem.endswith("_d") or "test" in stem:
                continue
            shutil.copy2(pyd, out_dir / pyd.name)
            pyd_count += 1
        # Native support DLLs used by extensions (ssl, ffi, sqlite, tcl, tk, zlib, etc.)
        for dll in sorted(dlls_src.glob("*.dll")):
            stem = dll.stem.lower()
            if stem.endswith("_d") or "test" in stem:
                continue
            shutil.copy2(dll, out_dir / dll.name)

    # Tcl/Tk data folders (required for _tkinter and Tkinter GUIs)
    tcl_src = dev.base / "tcl"
    if tcl_src.is_dir():
        tcl_dest = out_dir / "tcl"
        if not tcl_dest.exists():
            shutil.copytree(tcl_src, tcl_dest, ignore=shutil.ignore_patterns("*.lib", "*.sh"))
        print("  + tcl runtime data folder")

    print(f"  + {pyd_count} extension modules (.pyd)")
